### ISSUE TITLE
Registering a new account fails 

### ISSUE THREAD

**Issue by Aruee** [eXfio/CucumberSync#3]
I just wanted to try this application, this is what I get when I try to create a new account from within the app... 

![tmp_1420-screenshot_2016-10-07-10-55-32-1042560828](https://cloud.githubusercontent.com/assets/6168669/19184345/f0987c04-8c7c-11e6-89e9-972a26595566.jpg)

**Comment by nickel-chrome** [comment]
Hi @Aruee,

I've had some problems with my hosting provider and unfortunately until it is addressed I need to occasionally give one of the daemons a nudge.

It passed a sanity test for me this morning and should now be working correctly.
